name: .NET
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'
        
     # Add NuGet Sources

    - name: Create Local NuGet Directory
      run: mkdir ~/nuget

    - name: Add Local Nuget Source
      run: dotnet nuget add source ~/nuget

    - name: Add GGroupp NuGet Source
      run: >
        dotnet nuget add source ${{ secrets.GG_NUGET_SOURCE_URL }}
        -n ggroupp
        -u ${{ secrets.GG_NUGET_SOURCE_USER_NAME }}
        -p ${{ secrets.GG_NUGET_SOURCE_USER_PASSWORD }}
        --store-password-in-clear-text

    # AzureUser.Get.InOut.csproj

    - name: Restore AzureUser.Get.InOut.csproj
      run: dotnet restore ./src/*/*/AzureUser.Get.InOut.csproj

    - name: Build AzureUser.Get.InOut.csproj
      run: dotnet build ./src/*/*/AzureUser.Get.InOut.csproj --no-restore  -c Release

    - name: Pack AzureUser.Get.InOut.csproj
      run: dotnet pack ./src/*/*/AzureUser.Get.InOut.csproj --no-restore -o ~/nuget  -c Release

    # AzureUser.Get.Api.csproj

    - name: Restore AzureUser.Get.Api.csproj
      run: dotnet restore ./src/*/*/AzureUser.Get.Api.csproj

    - name: Build AzureUser.Get.Api.csproj
      run: dotnet build ./src/*/*/AzureUser.Get.Api.csproj --no-restore  -c Release

    - name: Pack AzureUser.Get.Api.csproj
      run: dotnet pack ./src/*/*/AzureUser.Get.Api.csproj --no-restore -o ~/nuget  -c Release

    # Geolocation.Get.InOut.csproj

    - name: Restore Geolocation.Get.InOut.csproj
      run: dotnet restore ./src/*/*/Geolocation.Get.InOut.csproj

    - name: Build Geolocation.Get.InOut.csproj
      run: dotnet build ./src/*/*/Geolocation.Get.InOut.csproj --no-restore  -c Release

    - name: Pack Geolocation.Get.InOut.csproj
      run: dotnet pack ./src/*/*/Geolocation.Get.InOut.csproj --no-restore -o ~/nuget  -c Release

    # Geolocation.Get.Api.csproj

    - name: Restore Geolocation.Get.Api.csproj
      run: dotnet restore ./src/*/*/Geolocation.Get.Api.csproj

    - name: Build Geolocation.Get.Api.csproj
      run: dotnet build ./src/*/*/Geolocation.Get.Api.csproj --no-restore  -c Release

    - name: Pack Geolocation.Get.Api.csproj
      run: dotnet pack ./src/*/*/Geolocation.Get.Api.csproj --no-restore -o ~/nuget  -c Release

    # Geolocation.Get.Tests

    - name: Restore Geolocation.Get.Tests
      run: dotnet restore ./src/*/*/Geolocation.Get.Tests.csproj

    - name: Test Geolocation.Get.Tests
      run: dotnet test ./src/*/*/Geolocation.Get.Tests.csproj --no-restore  -c Release

    # Push

    - name: Push Packages
      if: ${{ github.ref == 'refs/heads/main' }}
      run: >
        dotnet nuget push "../../../nuget/*.nupkg" -s ${{ secrets.GG_NUGET_SOURCE_URL }}
        -k ${{ secrets.GG_NUGET_SOURCE_USER_PASSWORD }}
        --skip-duplicate
